### ISSUE TITLE
[Win8][IE11] mathjax-sre fails to load

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-a11y#124]

**Comment by pkra** [comment]
The file seems to time out.

**Comment by pkra** [comment]
Reproduce on http://s.codepen.io/pkra/debug/yOWrWQ.

**Comment by pkra** [comment]
Also reproduces on Windows 10.

**Comment by zorkow** [comment]
But the file is there, isn't it?

**Comment by pkra** [comment]
Yes. it works fine in FF on the same system and elsewhere.

**Comment by pkra** [comment]
Fixes
