### ISSUE TITLE
[Win10+Edge] speech text garbled

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-a11y#125]
Maybe a regression of the xpath problem? Or maybe the build process?

**Comment by zorkow** [comment]
It tries to pick up the json and wgxpath file at the wrong location. What will be the final URL for that?

**Comment by pkra** [comment]
Can't it be relative like others URLs?

**Comment by zorkow** [comment]
Good point. I've never tried that.

**Comment by dpvc** [comment]
I would expect that you could use `MathJax.Ajax.config.path["SRE"]`.  A relative URL would be relative to the page that loaded SRE, not the location of SRE itself.

**Comment by pkra** [comment]
@dpvc sorry, yes, I meant the path setting.

**Comment by zorkow** [comment]
The problem is that currently, unless explicitly set, sre takes a default URL (which no longer exists for MathJax since we've moved the github repo).

**Comment by pkra** [comment]
Fixed.
