### ISSUE TITLE
Pop-up appears when printing

### ISSUE THREAD

**Issue by realityTorrent** [mathjax/MathJax-a11y#159]
![capture](https://cloud.githubusercontent.com/assets/6150997/19597020/467cbf70-9792-11e6-95f5-08870349346d.PNG)
I have a website where the user can print out the current page which consists of various mathematical formulas which I use mathJax to format. The problem is that this has started to pop-up at the bottom of the screen when printing:

`Loading [Contrib]/a11y/accessibility-menu.js`

Any idea what is wrong?

**Comment by pkra** [comment]
It's hard to tell much from a screenshot, I'm afraid. Most likely, MathJax had not finished loading all components -- the gray box is MathJax's processing message box; you can disable it via the MathJax configuration, see `showProcessingMessages` and `messageStyle` in http://docs.mathjax.org/en/latest/options/hub.html.

**Comment by realityTorrent** [comment]
I see, so either I make sure MathJax is fully loaded (though worth mentioning is that its not interfering with the rendering of the formulas) or disable the processing message box. I feel inclined to go for the latter. Thank you sir for you help!

**Comment by pkra** [comment]
No problem. The interaction between printing and JavaScirpt is unfortunately messy in most situations/browsers.
