### ISSUE TITLE
Unicode symbol for embellished relations

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax-a11y#163]
Relation symbols made up of more than one symbol get a mathml-like element as collapse symbol:
a =_2 b =_2 c =_2 d
collapses to
◂mo(=)mn(2)⋯▸

On the other hand embellished operators work. E.g.,
a +_2 b +_2 c +_2 d
collapses to
◂+▸

**Comment by dpvc** [comment]
I have made a pull request that should fix this.

**Comment by pkra** [comment]
This was fixed via #169
