### ISSUE TITLE
Incorrect summary for collapsed square

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax-a11y#176]
For example in Cauchy-Schwarz, when left-most sigma summation is collapsed the full details are spoken.

**Comment by pkra** [comment]
This seems to have been fixed.

**Comment by zorkow** [comment]
It still does it for me. Are you sure you have collapsed the correct part? It's the entire left part of inequality.

**Comment by zorkow** [comment]
This is now fixed in SRE [PR 164](https://github.com/zorkow/speech-rule-engine/pull/164)

**Comment by pkra** [comment]
> It still does it for me. Are you sure you have collapsed the correct part? It's the entire left part of inequality.

Thanks. Yes, the problem persists for me, too.

**Comment by zorkow** [comment]
Problem is solved in latest release (tested with 2.7.2-beta.1).
