### ISSUE TITLE
Labs no longer working with CDN

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax-a11y#199]
Needs to be changed to the cdnjs URL.

**Comment by pkra** [comment]
Maybe rawgit instead?

**Comment by zorkow** [comment]
We should probably also merge master into gh-pages, as otherwise the changes in #200 will not have any effect.

**Comment by pkra** [comment]
> We should probably also merge master into gh-pages, a

See #201

**Comment by dpvc** [comment]
CDN changes fixed in PR #200.  Merged.

**Comment by pkra** [comment]
https://github.com/mathjax/MathJax-a11y/search?utf8=%E2%9C%93&q=cdn.mathjax.org&type= still has two hits.
