### ISSUE TITLE
switch github pages to master branch

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-a11y#201]
It's a pain to keep in sync with master, now we can switch, https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/.

It takes a bit of work updating the readme etc.

**Comment by pkra** [comment]
After #199, I've changed the settings so that github.io is now using the master branch.

Leftovers:

* update Readme (in particular link, to documentation page).
* delete gh-pages branch.

**Comment by pkra** [comment]
@zorkow there's another set of slides only on gh-pages. Are these worth preserving in master?

**Comment by zorkow** [comment]
That the AHG slides? Yes, I think they are worth preserving. They give a hands-on description how to integrate MathJax/A11Y into web pages.

**Comment by zorkow** [comment]
I might even have the solutions for the exercise somewhere. I can look for that and update the slides.

**Comment by pkra** [comment]
Thanks, Volker.

**Comment by pkra** [comment]
I've deleted the gh-pages branch which is the final piece for this.
