### ISSUE TITLE
New SRE version 

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax-a11y#208]
Integrate latest SRE (v2.0.0-beta.3) that uses js instead of json file extensions for speech mappings,  to avoid cdnjs problems. 

@dpvc Do we need a new MathJax point release for that?

**Comment by pkra** [comment]
> Do we need a new MathJax point release for that?

Either way, we need a new MathJax-a11y release.

**Comment by pkra** [comment]
E.g., https://github.com/mathjax/MathJax-a11y/blob/master/Gruntfile.js#L13 needs to be changed.

**Comment by pkra** [comment]
This was fixed  via #209
