### ISSUE TITLE
spacing lost when enrichment is active

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-a11y#217]
Moving this upstream from https://github.com/mathjax/MathJax/issues/1833.

Example `\[ \begin{cases} u_1 =a, \\ u_{n+1} =r + u_{n}, \end{cases} \qquad\qquad\qquad \begin{cases} v_1 =a, \\ v_{n+1} =rv_{n}. \end{cases} \]`. 

The spacing is lost during enrichment.

**Comment by zorkow** [comment]
Same as https://github.com/mathjax/MathJax/issues/1833. Solve in #218 .
