### ISSUE TITLE
No aria-label for some math

### ISSUE THREAD

**Issue by garagebrewer** [mathjax/MathJax-a11y#225]
I have some expressions that do not get the correct aria-label.  It just says aria-label="math".  Other expressions work fine.  I'm including a sample HTML that reproduces the problem.  As far as I can tell, it seems related to the space in the expression.  "4 1/3" does not ready but on their own, "4" does read correctly and "1/3" does as well.
[math-test.html.zip](https://github.com/mathjax/MathJax-a11y/files/1669138/math-test.html.zip)

**Comment by zorkow** [comment]
Thanks for reporting this. I'm afraid I can't reproduce it. I get a descriptive aria label reading:
4 ⁢ open ( 1 divided by 3 close
Can you tell me the exact versions of MathJax and SRE? 
The only other issue I can see with your file is that the configuration script tag should normally come before the MathJax source script tag in the DOM.

**Comment by dpvc** [comment]
@zorkow, their test file is not correct.  You need to remote the parentheses to get the issue.  It should be `` `4 1/3` `` not `` `4(1/3)` ``.

**Comment by zorkow** [comment]
Thanks, @dpvc . I can reproduce the problem now.

**Comment by zorkow** [comment]
Problem fixed upstream and should be in next release.
