### ISSUE TITLE
Broken links to demo pages on master/docs/README.md

### ISSUE THREAD

**Issue by jfine2358** [mathjax/MathJax-a11y#227]
As subject. The page

- https://github.com/mathjax/MathJax-a11y/blob/master/docs/README.md

has links to 

- http://mathjax.github.io/MathJax-RespEq/examples/Struik-speech.html
- https://mathjax.github.io/MathJax-RespEq/Semantics-Lab/walker/

which are HTML 404 errors (sayting there isn't a GitHub pages site here).
The URL https://mathjax.github.io/ is also a 404.

However, this URL is good, and is presumably the one I want.

- https://mathjax.github.io/MathJax-a11y/examples/Struik-speech.html

**Comment by zorkow** [comment]
Thanks for finding and reporting those. The links must have survived the renaming of the repository and now the grace period for github forwarding the old links seems to have run out. 
PR #228 corrects the broken links and updates the documentation to the latest release.
