### ISSUE TITLE
explorer.js: navigate levels in  an align environment

### ISSUE THREAD

**Issue by cmhughes** [mathjax/MathJax-a11y#234]
Thank you very much for all of the terrific work on `MathJax` and `explorer.js`.

background
-
I'm using the `explorer.js` extension to navigate 'bit-by-bit' through equations. 

Using the minimum working example below, when I navigate to the (single line) display math, and press `CTRL + SPACE` the equation is highlighted, and I can *explore* the different levels by using the UP/DOWN arrows (as detailed in https://www.mathjax.org/mathjax-accessibility-extensions-v1-now-available/). 

Indeed, if I have `Subtitles` turned on, then I can see the `Level` by pressing space. This is wonderful and very helpful!

the problem
-
If I navigate to the `align*` environment, I do not have any option to navigate within levels in the align environment. If I have `Subtitles` turned on, the only piece of information that I can view within the `align*` environment is `StartLayout....EndLayout` which gives me all of the information in one go, but I can not interrogate it 'bit by bit'.

the question
-
Is it possible to configure `explorer.js` so that I can navigate on different levels within an `align*` (or similar, e.g. matrix, etc) environment?

`mwe.html`
-
```
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content=
  "width=device-width, initial-scale=1">
  <!-- MathJax configuration -->
  <script type="text/x-mathjax-config">

  MathJax.Hub.Config({ 
  extensions: ["[Contrib]/a11y/accessibility-menu.js"], 
  menuSettings: { 
  collapsible: false, 
  autocollapse: false, 
  explorer: {
    walker: 'semantic',         // none, syntactic, semantic
    highlight: 'flame',           // none, hover, flame
    background: 'red',           // blue, red, green, yellow, cyan, magenta, white, black
    foreground: 'red',         // black, white, magenta, cyan, yellow, green, red, blue
    speech: true,                // true, false
    generation: 'eager',          // eager, mixed, lazy
    subtitle: true,              // true, false
    ruleset: 'mathspeak-default',
  }}}); 
  </script>
  <script type="text/javascript" src=
  "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
</head>
<body>
  <p>Display math:</p>
  \[
	1+2+\frac{3}{4} = x + y
  \]
  <p>Aligned</p>
\begin{align*}
1&=2\\
 3&=4
\end{align*}
</body>
</html>
```

**Comment by pkra** [comment]
You'll need to update to the latest release to get the much improved table walker.

**Comment by cmhughes** [comment]
Thanks, that sounds optimistic. Could you let me know how I do that?

**Comment by zorkow** [comment]
Once you've updated you should change the explorer options
`walker: 'table'`
The `generation` option, I believe is now obsolete. But no harm if you keep it.

A full list of keyboard commands for table walking and jumping, cursor virtualisation etc. is 
here:
http://zorkow.github.io/speech-rule-engine/resources/www/keybindings.html

**Comment by pkra** [comment]
@zorkow it would be good to link to that page from nhttps://mathjax.github.io/MathJax-a11y/

**Comment by cmhughes** [comment]
Thank you very much indeed, this is absolutely fantastic. 

Following your help, I have been able to navigate single-line and multi-line mathematical expressions and equations both with and without assistive technologies. 

Your work on `MathJax` has massive positive implications for our work on accessibility in Maths & Stats at The Open University. Thank you!
