### ISSUE TITLE
Equation labels

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-a11y#9]
We don't handle them yet, right?

My gut feeling would be that they will never get collapsed completely (but might in themselves if they're huge). As in

```
<...> (<...>)
```

etc.

**Comment by dpvc** [comment]
It looks like the label is not getting any semantic tags, so it doesn't trigger the collapsing code (which relies on the semantics).  But there is nothing stopping the collapsing from being handled that way, if the semantics were added (and tags *can* include math, so it might be worth doing the semantic traversal).

**Comment by pkra** [comment]
> It looks like the label is not getting any semantic tags, so it doesn't trigger the collapsing code (which relies on the semantics). 

Ah! I'll open an issue on speechruleengine

> But there is nothing stopping the collapsing from being handled that way, if the semantics were added (and tags can include math, so it might be worth doing the semantic traversal).

Excellent.

Should we add a rule that a labeled equation should not be completely collapsed? but at most to the structure I so poorly tried to describe above? (I.e., one "collapsedible" for the equation and one for the label)

**Comment by dpvc** [comment]
I don't think individual rows will collapse -- only matrices as a whole, and then only those that are marked as actual matrices or vectors.  Those that are used for alignment layouts won't be marked that way, so should not collapse.  But the contents of the cells can, so your desired result would be possible.

The only issue right now is that a normal `\tag{}` will produce a label that is a single `mtext` element (including the parentheses), so it will either collapse as a whole or not collapse at all.  So `(...)` won't happen.  We would need to do something special to make that happen.

If you do a tag like the following

    ... \tag{$math$}

then the parentheses will be separate `mtext` elements, and the math inside will be collapsible if complex enough.

**Comment by pkra** [comment]
> I don't think individual rows will collapse -- only matrices as a whole, and then only those that are marked as actual matrices or vectors. 

Thanks. Once again, I forget that labels only happen in mtable rows (I blame sleep deprivation); this is stupid...

> The only issue right now is that a normal \tag{} will produce a label that is a single mtext element (including the parentheses), so it will either collapse as a whole or not collapse at all.

Right.

>  We would need to do something special to make that happen.

Now I'm not sure anymore. Will think about it some more for the next F2F.

**Comment by zorkow** [comment]
For the record: There is currently no recognition of components of layout tables (e.g., equation labels, aligned equalities etc.) They are mostly correctly categorised as the semantic class table, as opposed to vector, matrix, cases etc., but that is it.

**Comment by pkra** [comment]
Update:

* voicing is now working in rows and their labels. 
  * By design labels cannot be explored and are voiced only when reading the full table row (at beginning of row).
* auto-collapse seems to struggle a bit but I don't remember what we can expect in tables. 
  * It does collapse the label content; in edge cases we have the problem that keyboard users can't reach the label to uncollapse (and thus voicing will only give the summary from the collapsed content)

So I think this can be closed as fixed; it is working with some minor and intentional limitations.
