### ISSUE TITLE
[a11y extension] location location location

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-a11y#95]
I would like to propose to move the dist and build files back into this repo.

Since we're not putting the final extension in the third-party repo, we might as well push them to the CDN from this repo; the other one just adds noise and confusion.

**Comment by dpvc** [comment]
I'm OK with moving things back.

I'm afraid I'm a little out of the loop on where the files are to be stored.  Not in the third-party repository, but on the CDN, somewhere.  What is the URL going to be for that?

I'm assuming the unpacked versions are not going to be available on the CDN, right?  So the `diet` folder represents what will be on the CDN?

**Comment by pkra** [comment]
> What is the URL going to be for that?

I was thinking to still upload this to where the third-party-repo ends up, i.e., `cdn.mathjax.org/mathjax/contrib`.

> I'm assuming the unpacked versions are not going to be available on the CDN, right? So the dist folder represents what will be on the CDN?

That's what I was thinking. But it's not very important to me, 1/10.

**Comment by pkra** [comment]
As per F2F, move things back here, rename this to `mathjax-a11y`

**Comment by pkra** [comment]
I was trying to tackle this (to get into the code and start #97) but the grunt-file seems a bit odd (and misses some resources). 

I've begun writing a fresh one.

@zorkow any suggestions on providing the closure compiler? (Or perhaps publish mathjax-sre as a separate module to npm?)

**Comment by pkra** [comment]
Here's what I came up with. https://gist.github.com/pkra/fe1bd64ba2053665923d07e2747883da

**Comment by pkra** [comment]
Quick smoke test indicates this creates a viable distribution.

**Comment by pkra** [comment]
I've made some minor changes to make repeated builds slightly less of pain.

**Comment by pkra** [comment]
I with #113 merged, I think we can shut down the old repo and rename this one.

Any objections?

**Comment by dpvc** [comment]
OK.  If you are going to do that now, I will wait to make the renaming changes that we discussed in conference today until after that is done.

**Comment by pkra** [comment]
> I will wait to make the renaming changes that we discussed in conference today until after that is done.

I don't think there's a need to wait. GitHub redirects all things. But this can wait until @zorkow is back.

**Comment by pkra** [comment]
I've deleted the old repo (but still have a local copy if we deed one).

I'm confused by myself. Do we call this repo `MathJax-a11y` (stated earlier as result of F2F) or `MathJax-Accessibility` (which I put in the readme)

**Comment by pkra** [comment]
Ok, I checked the F2F notes and it says `a11y`. 

Done but can obviously be revisited at the F2F.
